applications/empleados/urls.py
from django.urls import path
# vistas importadas
from . import views

app_name = "empleados_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),

    path(
        'listar-empleados/',
        views.listAllEmpleados.as_view(),
        name='empleados-all'),

    path(
        'listar-by-area/<short_name>/',
        views.listByAreaEmpleado.as_view(),
        name='empleados_all'
    ),

    path(
        'lista-empleados-admin/',
        views.listEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),

    path(
        'buscar-empleado/',
        views.listEmpleadosbykword.as_view()
    ),

    path('lista-habilidades-empleados/',
         views.listaHabilidadesByEmpleados.as_view()),

    # pk hace referencia al id que se crea por defecto en el modelo
    path(
        'ver-empleados/<pk>/',
        views.empleadoDetailView.as_view(),
        name='empleado_detail',

    ),

    path(
        'succes-empleado/',
        views.succesView.as_view(),
        name='correcto'
    ),

    path(
        'add-empleado/',
        views.empleadoCreateView.as_view(),
        name='empleado_add'
    ),

    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),

    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
# vistas importadas
from applications.home.views import IndexView
# para las url de las imagenes que se cargan por empleado
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from applications.departamentos.models import Departamento

from ckeditor.fields import RichTextField


# Create your models here.


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleado'

    def __str__(self):
        return str(self.id) + '  ' + self.habilidad


class Empleado(models.Model):
    JOB_CHOICES = (
        ('O', 'GERENTE'),
        ('1', 'COORDINADOR'),
        ('2', 'AUX ADMINISTRATIVO'),
        ('3', 'AUX SOPORTE'),
        ('4', 'AUX OPERATIVO'),
        ('5', 'CONDUCTOR'),
        ('6', 'SUPERVISOR'),
        ('7', 'SERVICIOS GENERALES'),
    )

    first_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('Apellido', max_length=50)
    full_name = models.CharField(
        'Nombre completos',
        max_length=120,
        blank=True
    )
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    # Relaciono el modelo de departamento con el de empleados, relacion de uno a muchos
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    #img = models.ImageField('', upload_to=None, height_field=None, width_field=None, max_length=None)

    # Relacion de muchos a muchos,
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Mis empleados'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['id']
        unique_together = ('first_name', 'last_name')  # que no se repita

    def __str__(self):
        return str(self.id) + '  ' + self.first_name + '  ' + self.last_name

applications/empleados/views.py
from django.shortcuts import render
# importo reverse_lazy para que las urls permitan especificar urls de forma segura
from django.urls import reverse_lazy
# Vista generica que muestra html
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

# Create your views here. or logic controller

from .models import Empleado
# forms
from .form import EmpleadoForm
# Listar empleados


class InicioView(TemplateView):
    """Vista que carga la pagina inicio"""
    template_name = 'inicio.html'


class listAllEmpleados(ListView):
    template_name = 'empleados/list_all.html'
    paginate_by = 4

    def get_queryset(self):

        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            # el icontains busca coincidencias dentro de lo que exista en palabra_clave. Se elige full name ya que siempre tiene un espacio intermedio
            full_name__icontains=palabra_clave
        )

        return lista


class listEmpleadosAdmin(ListView):
    template_name = 'empleados/list_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

# Detalles del empleado


class empleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleados/detail_empleados.html"

    def get_context_data(self, **kwargs):
        context = super(empleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


# Listar empleados por area


class listByAreaEmpleado(ListView):
    """Lista de empleados"""
    template_name = 'empleados/list_by_area.html'
    context_object_name = 'empleados'
    # este queryset hace que devuelva los empleados de un area especifica

    def get_queryset(self):

        filtro = self.kwargs['short_name']
        palabra_clave = self.request.GET.get('kword', '')
        if palabra_clave != '':
            lista = Empleado.objects.filter(
                full_name__icontains=palabra_clave
            )
            return lista
        else:
            lista = Empleado.objects.filter(
                departamento__short_name=filtro)
        return lista

        # esta es la forma en la que se recoge una variable de la url para ser procesada
        # area = self.kwargs['short_name']
        # lista = Empleado.objects.filter(
        #     departamento__name=area
        # )
        # return lista

# Listar empleados por palabra clave


class listEmpleadosbykword(ListView):
    """Lista empleados por palabra clave"""
    template_name = 'empleados/by_kword.html'
    # Re definir el nombre que nos va a devolver el listview
    context_object_name = 'empleados'
    # Funcion que permite captar y procesar lo que contiene la url

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )

        return lista

# Listar habilidades por empleado


class listaHabilidadesByEmpleados(ListView):
    template_name = 'empleados/by_habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        # Funcion que permite captar y procesar lo que contiene la url
        id_habilidad = self.request.GET.get("id_persona", '')
        # recuperando un unico registro de la base de datos
        empleado = Empleado.objects.get(id=id_habilidad)

        return empleado.habilidades.all


class succesView(TemplateView):
    template_name = "empleados/succes.html"

# Con esta clase se evidencia como se ingresan cosas a la base de datos
# CreateView


class empleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleados/add.html"
    form_class = EmpleadoForm
    # se debe especificar obligatoriamente una pagina que se cargue al momento de ejecutar el html
    # con ('__all__') se muestran todos, con['datoEspecifico']
    success_url = reverse_lazy('empleados_app:empleados_admin')
    # Funcion que acepta datos solo si son correctamente ingresados en  la solicitud de la vista

    def form_valid(self, form):
        # aca se generara y guardar el full name a partir del first_name y el last_name
        empleado = form.save()
        # print(empleado)
        # Ahora si se envia al modelo
        empleado.full_name = empleado.first_name + '  ' + empleado.last_name

        empleado.save()
        return super(empleadoCreateView, self).form_valid(form)

# Vista generica que nos permite actualizar registros


class EmpleadoUpdateView(UpdateView):
    template_name = "empleados/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('empleados_app:empleados_admin')

    def post(self, request, *args: str, **kwargs):
        self.object = self.get_object()
        # devuelve un diccionario por lo que podemos acceder a las claves
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):

        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleados/delete.html"
    success_url = reverse_lazy('empleados_app:empleados_admin')

templates/empleados/add.html
{% extends 'base.html' %}

{% block title %}

Registrar | Empleado
    
{% endblock title %}
    

{% block body %}

{% include "includes/header.html" %}  
<!-- CreateView tiene una palabra reservada que tiene pre cargado un codigo html y responde al nombre de "form" el cual muestra los cuadros de dialogo incluidos en el
"fiels" de la vista -->
<div class="grid-container">
    <h1 class="cell">Registrar persona</h1>  
    <form class="cell grid-x grid-margin-x" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="medium-6 cell">
            <label for="">Nombre:
                {{form.first_name}}
            </label>
        </div>

        <div class="medium-6 cell">
            <label for="">Apellido:
                {{form.last_name}}
            </label>
        </div>

        <div class="medium-6 cell">
            <label for="">Cargo:
                {{form.job}}
            </label>
        </div>

        <div class="medium-6 cell">
            <label for="">Departamento:
                {{form.departamento}}
            </label>
        </div>

        <div class="medium-12 cell">
            <label for="">Habilidades:
                {{form.habilidades}}
            </label>
        </div>

        <div class="medium-12 cell">
            <label for="">Avatar:
                {{form.avatar}}
            </label>
        </div>

        <div class="medium-12 cell">
            <button class="button success" type="submit">Guardar</button>
        </div>
        </div>
    </form>
</div>

    
{% endblock body %}

templates/empleados/by_habilidades.html
<h1>Lista de habilidades de empleados</h1>
<!-- Con el siguiente token protegemos el metodo GET -->
<form method="GET">{% csrf_token %}
    <input type="text" name="id_persona" id="id_persona" placeholder="Ingrese un ID">
    <button type="submit">Buscar</button>
</form>

<h3>Lista de habilidades</h3>

<ul>
    {% for h in habilidades  %}

    <li>{{ h }}</li>
    
    {% endfor %}
</ul>
    

templates/empleados/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<!-- Con el siguiente token protegemos el metodo GET -->
<form method="GET">{% csrf_token %}
    <input type="text" name="kword" id="kword" placeholder="Ingrese una plabra clave">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>

<ul>
    
    {% for e in empleados  %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

templates/empleados/delete.html
{% extends 'base.html' %}


{% block title %}
Eliminar | Empleado    
{% endblock title %}
    

{% block body %}

{% include 'includes/header.html' %}

<div class="grid container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.full_name }}</h1>

        <form class="cell" method="post">{% csrf_token %}
            <div class="callout alert">
                <h5>¿Desea Eliminar a {{ object.full_name }}?</h5>
                <p>Recuerde que al eliminar a {{ object.full_name }} lo eliminara por completo de los registros de la compañia.</p>
                <button type="submit" class="alert button">ELIMINAR</button>
            </div>
        </form>

    </div>
</div>
    
{% endblock body %}
    


<h1>Se eliminara el empleado</h1>

templates/empleados/detail_empleados.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Detalles | {{ object.full_name }} {% endblock title %}

<!-- INICIO DEL BODY -->

{% block body %}
{% include 'includes/header.html' %}
<h1 class="cell">Detalles de Empleados</h1>
<div class="cell">
  <table>
    <thead>
      <tr>
        <th width="200">ID</th>
        <th>NOMBRE</th>
        <th>APELLIDOS</th>
        <th>DEPARTAMENTO</th>
        
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{empleado.id}}</td>
        <td>{{empleado.first_name}}</td>
        <td>{{empleado.last_name}}</td>
        <td>{{empleado.departamento.short_name}}</td>
      </tr>
    </tbody>
  </table>    
</div>

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
      <div class="card cell large-4 " style="width: 300px;">
        <div class="card-divider">
          {{ empleado.get_job_display }}
       </div>
      
      
      {% if empleado.avatar %}

        <img src="{{ empleado.avatar.url }}">
      {% else %}
        <h5>Cargue una imagen para este empleado</h5>
        <img src="{% static 'img/AdminLTELogo.png' %}" alt="">
      {% endif %}
      <div class="card-section">
        <h4> {{ empleado.full_name }} </h4>
        <p> <span class="label"> Habilidades</span></p>

        <ul class="vertical menu">
          
          {% for hab in empleado.habilidades.all  %}
            <li>{{hab.habilidad}}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>



{% endblock body %}
    
<!-- FIN DEL BODY -->

templates/empleados/list_all.html
{% extends 'base.html' %}

{% block title %} Lista | Empleados {% endblock title %}

{% block body %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>

        <form method="get" class="cell grid-x grid-margin-x">{% csrf_token %}
            <div class="cell large-6">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-5">
                <button class="submit success button">Buscar</button>
            </div>          
        </form>

        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRE</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list%}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id %}">Ver</a></td>  
                    </tr>
                    {% endfor %}
                </tbody>
              </table>

            </div>
            <!-- INICIO DE PAGINACION -->
            <div class cell>
                
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number   %} 
                        <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                        <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        {% endif %}
                        {% endfor %} 
                             
                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>    
                        {% endif %}
                    </ul>
                </nav>    
                {% endif %}
                    
                
            </div>
            <!-- FIN DE PAGINACION -->
    </div>
</div>
    
{% endblock body %}
    

templates/empleados/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista empleados por departamento
{% endblock title %}


{% block body %}

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por Area</div>
            <div class="cell">

                <table>
                    <thead>
                        <tr>
                        <th width="200">ID</th>
                        <th>NOMBRE</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in object_list%}
                            <tr>
                                <td>{{e.id}}</td>
                                <td>{{e.first_name}}</td>
                                <td>{{e.last_name}}</td>
                                <td>{{e.departamento}}</td>
                                <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id %}">Ver</a></td>  
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>

        </div>

    </div>
    
{% endblock body %}
    
    

<!-- <h1>Lista de empleados por departamento</h1>

<ul>
    {% for e in object_list%}
        <li>
            {{e}}
        </li>
    {% endfor %}
</ul> -->

templates/empleados/list_empleados.html
{% extends 'base.html' %}

{% block title %} Lista | Empleados {% endblock title %}

{% block body %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>

        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRE</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list%}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'empleados_app:modificar_empleado' e.id %}" >Editar</a>
                        </td>  
                        <td>
                            <a class="button alert" href="{% url 'empleados_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>

            </div>
            <!-- INICIO DE PAGINACION -->
            <div class cell>
                
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number   %} 
                        <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                        <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        {% endif %}
                        {% endfor %} 
                             
                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>    
                        {% endif %}
                    </ul>
                </nav>    
                {% endif %}
                    
                
            </div>
            <!-- FIN DE PAGINACION -->
    </div>
</div>
    
{% endblock body %}
    

templates/empleados/succes.html
<h1>FELICITACIONES!!! EL EMPLEADO SE GUARDO AL PELO</h1>

templates/empleados/update.html
{% extends 'base.html' %}

{% block title %}
Update | Empleados    
{% endblock title %}

<!-- INICIA EL BODY -->
{% block body %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" action="" method="post">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres
                        {{form.first_name}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Apellidos
                        {{form.last_name}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Trabajo
                        {{form.job}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Departamento
                        {{form.departamento}}
                    </label>
                </div>

                <div class="cell large-6">
                    <label>Habilidades extra
                        {{form.habilidades}}
                    </label>
                </div>
                
                <div class="cell">
                    <button class="button success" type="submit">Guardar</button>
                </div>
                
            </form>
        </div>
    </div>

</div>
   
{% endblock body %}
<!-- FINALIZA EL BODY -->