applications/departamentos/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'),
    path(
        'listar-departamento/',
        views.DepartamentoListView.as_view(),
        name='listar-departamento'),
]

applications/empleados/urls.py
from django.urls import path
# vistas importadas
from . import views

app_name = "empleados_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),

    path(
        'listar-empleados/',
        views.listAllEmpleados.as_view(),
        name='empleados-all'),

    path(
        'listar-by-area/<short_name>/',
        views.listByAreaEmpleado.as_view(),
        name='empleados_all'
    ),

    path(
        'lista-empleados-admin/',
        views.listEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),

    path(
        'buscar-empleado/',
        views.listEmpleadosbykword.as_view()
    ),

    path('lista-habilidades-empleados/',
         views.listaHabilidadesByEmpleados.as_view()),

    # pk hace referencia al id que se crea por defecto en el modelo
    path(
        'ver-empleados/<pk>/',
        views.empleadoDetailView.as_view(),
        name='empleado_detail',

    ),

    path(
        'succes-empleado/',
        views.succesView.as_view(),
        name='correcto'
    ),

    path(
        'add-empleado/',
        views.empleadoCreateView.as_view(),
        name='empleado_add'
    ),

    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),

    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
# vistas importadas
from applications.home.views import IndexView
# para las url de las imagenes que se cargan por empleado
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'empleados_app:empleados-all' %}">Listar</a>
        </li>
        <li>
          <a href="{% url 'departamento_app:listar-departamento' %}">Departamentos</a></li>
          <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo departamento</a></li>
          <li><a href="{% url 'empleados_app:empleados_admin' %}">Administrar</a></li>
        
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li> <a href="{% url 'empleados_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>