applications/empleados/urls.py
from django.urls import path
# vistas importadas
from . import views

app_name = "empleados_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),

    path(
        'listar-empleados/',
        views.listAllEmpleados.as_view(),
        name='empleados-all'),

    path(
        'listar-by-area/<short_name>/',
        views.listByAreaEmpleado.as_view(),
        name='empleados_all'
    ),

    path(
        'lista-empleados-admin/',
        views.listEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),

    path(
        'buscar-empleado/',
        views.listEmpleadosbykword.as_view()
    ),

    path('lista-habilidades-empleados/',
         views.listaHabilidadesByEmpleados.as_view()),

    # pk hace referencia al id que se crea por defecto en el modelo
    path(
        'ver-empleados/<pk>/',
        views.empleadoDetailView.as_view(),
        name='empleado_detail',

    ),

    path(
        'succes-empleado/',
        views.succesView.as_view(),
        name='correcto'
    ),

    path(
        'add-empleado/',
        views.empleadoCreateView.as_view(),
        name='empleado_add'
    ),

    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),

    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
# vistas importadas
from applications.home.views import IndexView
# para las url de las imagenes que se cargan por empleado
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/departamen/lista.html
{% extends 'base.html' %}


{% block title %}   
Listar Departamento
{% endblock title %}    


{% block body %}
    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 cell>Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos %}
                            <tr>
                                <td>{{ departamento.name }}</td>
                                <td>{{ departamento.short_name }}</td>
                                <td>
                                    <a class="button warning" href="{% url 'empleados_app:empleados_all' departamento.short_name %}">Ver Empleados.</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- INICIO DE PAGINACION -->
            <div class cell>
                
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number   %} 
                        <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                        <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        {% endif %}
                        {% endfor %} 
                             
                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>    
                        {% endif %}
                    </ul>
                </nav>    
                {% endif %}
                    
                
            </div>
            <!-- FIN DE PAGINACION -->
        </div>
    </div>

{% endblock body %}
    
    

templates/departamen/new_departamento.html
{% extends 'base.html' %}


{% block title %}
Agragar datos | Empleado    
{% endblock title %}
    


{% block body %}

{% include 'includes/header.html' %}

<h1>Registrar nuevo departamento</h1>


<div class="grid-container">
 
    <form class="cell callout grid-x grid-margin-x" action="" method="post" ">{% csrf_token %}

        <h3 class="cell">Datos empleado</h3>
        <div class="medium-6 cell">
            <label for="">Nombre:
                {{form.nombre}}
            </label>
        </div>

        <div class="medium-6 cell">
            <label for="">Apellido:
                {{form.apellido}}
            </label>
        </div>

        <h3 class="cell">Datos de departamento</h3>

        <div class="medium-6 cell">
            <label for="">Departamento:
                {{form.departamento}}
            </label>
        </div>
        <div class="medium-6 cell">
            <label for="">Nombre corto:
                {{form.short_name}}
            </label>
        </div>

        

        <div class="medium-12 cell">
            <button class="button success" type="submit">Guardar</button>
        </div>
        </div>
    </form>
</div>

{% endblock body %}


    

templates/departamen/prueba1.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>P1</title>
</head>
<body>
    <h1>Esto es una prueba para la app departamento desde el template</h1>
</body>
</html>